use master
go

create database Biblioteca
go

use Biblioteca
go

create table PRESTAMO
(	NroPrestamo	INT			NOT NULL,
	FechaPres	DATETIME	NOT NULL,
	IdEjemplar	INT			NOT NULL,
	FechaDev	DATETIME	NOT NULL,
	IdLector	INT			NOT NULL)
GO

CREATE TABLE EJEMPLAR
(	IdEjemplar	INT			NOT NULL,
	FechaIng	DATETIME	NOT NULL,
	EstadoCons	VARCHAR(50)	NOT NULL,
	IdLibro		INT			NOT NULL)
GO

CREATE TABLE LECTOR
(	IdLector	INT			NOT NULL,
	Telefono	INT			NOT NULL,
	ApecLec		VARCHAR(20)	NOT NULL,
	NomLec		VARCHAR(20)	NOT NULL,
	DirecLec	VARCHAR(20)	NOT NULL)
GO

CREATE TABLE LIBRO
(	IdLibro		INT			NOT NULL,
	Titulo		VARCHAR(30)	NOT NULL,
	Sumilla		VARCHAR(80)	NOT NULL,
	CantPag		INT			NOT NULL,
	IdEditorial	INT			NOT NULL)
GO

CREATE TABLE LIBRO_AUTOR
(	IdLibro		INT			NOT NULL,
	IdAutor		INT			NOT NULL,
	Capitulos	VARCHAR(20)	NOT NULL)
GO

CREATE TABLE EDITORIAL
(	IdEditorial	INT			NOT NULL,
	NomEdit		VARCHAR(40)	NOT NULL,
	DirEdit		VARCHAR(50)	NOT NULL,
	PaisEdit	VARCHAR(30) NOT NULL)
GO

CREATE TABLE AUTOR
(	IdAutoR		INT			NOT NULL,
	ApePaterno	VARCHAR(20)	NOT NULL,
	ApeMaterno	VARCHAR(20)	NOT NULL,
	NombAu		VARCHAR(30)	NOT NULL,
	PaisAu		VARCHAR(20)	NOT NULL,
	FeNacAu		DATETIME	NOT NULL)
GO

ALTER TABLE	PRESTAMO
ADD CONSTRAINT PKPrestamo
PRIMARY KEY (NroPrestamo)
GO

ALTER TABLE	EJEMPLAR
ADD CONSTRAINT PKEjemplar
PRIMARY KEY (IdEjemplar)
GO

ALTER TABLE	LECTOR
ADD CONSTRAINT PKLector
PRIMARY KEY (IdLector)
GO

ALTER TABLE	LIBRO
ADD CONSTRAINT PKlibro
PRIMARY KEY (IdLibro)
GO

ALTER TABLE	LIBRO_AUTOR
ADD CONSTRAINT PKLibro_Autor
PRIMARY KEY (IdLibro, IdAutor)
GO

ALTER TABLE	EDITORIAL
ADD CONSTRAINT PKEditorial
PRIMARY KEY (IdEditorial)
GO

ALTER TABLE	AUTOR
ADD CONSTRAINT PKAutor
PRIMARY KEY (IdAutor)
GO

ALTER TABLE PRESTAMO
ADD CONSTRAINT FKEjemplar
FOREIGN KEY (IdEjemplar)
REFERENCES EJEMPLAR
GO

ALTER TABLE PRESTAMO
ADD CONSTRAINT FKLector
FOREIGN KEY (IdLector)
REFERENCES LECTOR
GO

ALTER TABLE EJEMPLAR
ADD CONSTRAINT FKLibro
FOREIGN KEY (IdLibro)
REFERENCES LIBRO
GO

ALTER TABLE LIBRO
ADD CONSTRAINT FKEditorial
FOREIGN KEY (IdEditorial)
REFERENCES EDITORIAL
GO

ALTER TABLE LIBRO_AUTOR
ADD CONSTRAINT FKLibroAutor
FOREIGN KEY (IdLibro)
REFERENCES LIBRO
GO

ALTER TABLE LIBRO_AUTOR
ADD CONSTRAINT FKAutor
FOREIGN KEY (IdAutor)
REFERENCES AUTOR
GO